source 'https://rubygems.org'
gem 'execjs'
gem 'therubyracer'
gem 'yt'
gem 'jekyll', '>= 3.4.0'
gem 'jekyll-paginate'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
#gem 'pygments.rb'
gem 'jekyll-admin', group: :jekyll_plugins
